---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Run the Django syncdb command
  shell: . {{ virtualenv_path }}/bin/activate
         && . {{ virtualenv_path }}/bin/postactivate
         && cd {{ application_path }}
         && python manage.py syncdb --noinput
  when: run_django_syncdb
  tags: django

- name: Run Django South migrations
  shell: . {{ virtualenv_path }}/bin/activate
         && . {{ virtualenv_path }}/bin/postactivate
         && cd {{ application_path }}
         && python manage.py migrate --noinput
  when: run_django_south_migration
  tags: django

- name: Run Django collectstatic
  shell: . {{ virtualenv_path }}/bin/activate
         && . {{ virtualenv_path }}/bin/postactivate
         && cd {{ application_path }}
         && python manage.py collectstatic --noinput
  when: run_django_collectstatic
  tags: django

- name: Create development admin user
  shell: . {{ virtualenv_path }}/bin/activate
         && . {{ virtualenv_path }}/bin/postactivate
         && cd {{ application_path }}
         && python manage.py update_admin_user --username=admin --password=development
  when: development
  tags: django
