---
- name: restart celery workers
  service: name={{project_name}}-celeryworker state={{item}}
  with_items:
    - stopped
    - started
  sudo_user: root

- name: restart celery beat
  service: name={{project_name}}-celerybeat state={{item}}
  with_items:
    - stopped
    - started
  sudo_user: root
