---

- name: Celery | Create celery log directory
  file: path=/var/log/celery state=directory owner=wittl group=webapps

- name: Celery | Create celery pid directory
  file: path=/var/run/celery state=directory owner=wittl group=webapps

- name: Celery | Install CeleryBeat upstart jobs
  template: >
    src=upstart.celerybeat.conf.j2
    dest=/etc/init/{{project_name}}-celerybeat.conf
  notify:
    - restart celery beat
  tags:
    - celery

- name: Celery | Install Celery Worker upstart jobs
  template: >
    src=upstart.celeryworker.conf.j2
    dest=/etc/init/{{project_name}}-celeryworker.conf
  notify:
    - restart celery workers
  tags:
    - celery